id: P4D29AF4D
initial_creation_type: input
source_metadata:
  title: 'Mātṛceṭa: Śatapañcāśatka'
  language: zh
  volumes:
    908c97d2701f46368820405065daa3d6:
      title: 'Chapter 10: Mārgaāvatārastavaḥ'
      base_file: 'Chapter 10: Mārgaāvatārastavaḥ.txt'
      work_id: W7BA87F0F
    4646111622ec4a739bd3fb42f364ad03:
      title: 'Chapter 11: Duṣkarastavaḥ'
      base_file: 'Chapter 11: Duṣkarastavaḥ.txt'
      work_id: W997E5C4C
    2f3eca70f1a94618a53e0896e90067a8:
      title: 'Chapter 12: Kauśalastavaḥ'
      base_file: 'Chapter 12: Kauśalastavaḥ.txt'
      work_id: W24E5854A
    39549e04cbd64fc38c3170a8e0704416:
      title: 'Chapter 13: Ānṛṇyastavaḥ'
      base_file: 'Chapter 13: Ānṛṇyastavaḥ.txt'
      work_id: W66F79991
    2681b164922f4ec2a05658cd4acef961:
      title: 'Chapter 1: Upodghātaḥ'
      base_file: 'Chapter 1: Upodghātaḥ.txt'
      work_id: W6C5DA886
    489c63822c6b483091492b942eb829ec:
      title: 'Chapter 2: Hetustavaḥ'
      base_file: 'Chapter 2: Hetustavaḥ.txt'
      work_id: W1D643771
    c40f7e1f9ada4c01b7760b698f56916f:
      title: 'Chapter 3: Nirupamastavaḥ'
      base_file: 'Chapter 3: Nirupamastavaḥ.txt'
      work_id: W00D34AF1
    ea3d4a90213d4357aa9eccefcf4c97aa:
      title: 'Chapter 4: Adbhutastavaḥ'
      base_file: 'Chapter 4: Adbhutastavaḥ.txt'
      work_id: WA4EEAA64
    a79a0720963e4f5ebbafca619160ea22:
      title: 'Chapter 5: Rūpastavaḥ'
      base_file: 'Chapter 5: Rūpastavaḥ.txt'
      work_id: W29142204
    ea53091061ec4dc095ddf0dafa730e82:
      title: 'Chapter 6: Karuṇāstavaḥ'
      base_file: 'Chapter 6: Karuṇāstavaḥ.txt'
      work_id: W2A068A21
    a2cb1615648d42e0aaa9cbc8de97a23a:
      title: 'Chapter 7: Vacanastavaḥ'
      base_file: 'Chapter 7: Vacanastavaḥ.txt'
      work_id: W8AB8BA07
    af8cf47b598246459719ca6e67122028:
      title: 'Chapter 8: Śāsanastavaḥ'
      base_file: 'Chapter 8: Śāsanastavaḥ.txt'
      work_id: W7C302B0B
    30f3e06d99054e41b205be63bf0bbea9:
      title: 'Chapter 9: Praṇidhistavaḥ'
      base_file: 'Chapter 9: Praṇidhistavaḥ.txt'
      work_id: W697A17AF
    e688694f5543424bb206df55e5dbf7a4:
      title: Colophon
      base_file: Colophon.txt
      work_id: WA81606DA
    c73d42b572424a27a21438d607ec2321:
      title: Preface
      base_file: Preface.txt
      work_id: WBDE5E6D3
    7b177b49c6374d4a8b4612268382711d:
      title: Title
      base_file: Title.txt
      work_id: WBBCF6CFA
  chapter_to_tile: {}
created_at: '2022-03-01T23:38:25.008539'
last_modified_at: '2022-03-01T23:38:25.008550'
